CREATE TABLE CSM_ENTERPRISE 
(
  ENTERPRISE_NAME VARCHAR2(256 CHAR) NOT NULL 
, CONTACT_NAME VARCHAR2(255 CHAR) 
, CONTACT_EMAIL VARCHAR2(255 CHAR) 
, TELEPHONE VARCHAR2(255 CHAR) 
, FAX VARCHAR2(255 CHAR) 
, ADDRESS VARCHAR2(1024 CHAR) 
, CITY VARCHAR2(255 CHAR) 
, LOCALITY VARCHAR2(255 CHAR) 
, ZIP_CODE VARCHAR2(255 CHAR) 
, COUNTRY VARCHAR2(255 CHAR) 
, DESCRIPTION VARCHAR2(1024 CHAR) 
, ENTERPRISE_ID NUMBER(19, 0) NOT NULL 
, PARENT_ID NUMBER(19, 0) NOT NULL 
, HERITAGE VARCHAR2(2000 CHAR) NOT NULL 
, ENTERPRISE_LEVEL NUMBER(10, 0) NOT NULL 
, CONSTRAINT XPKCSM_ENTERPRISE PRIMARY KEY 
  (
    ENTERPRISE_NAME 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPKCSM_ENTERPRISE ON CSM_ENTERPRISE (ENTERPRISE_NAME ASC) 
      LOGGING 
      TABLESPACE WWFDATA 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 81920 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE ABCDATA 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 81920 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE UNIQUE INDEX XAK1CSM_ENTERPRISE ON CSM_ENTERPRISE (ENTERPRISE_ID ASC) 
LOGGING 
TABLESPACE WWFDATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 81920 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;
