CREATE TABLE CSM_ROLE 
(
  ROLE_ID NUMBER(19, 0) NOT NULL 
, ROLE_NAME VARCHAR2(255 CHAR) NOT NULL 
, ENTERPRISE_NAME VARCHAR2(256 CHAR) NOT NULL 
, DESCRIPTION VARCHAR2(1024 CHAR) 
, INHERITABLE NUMBER(1, 0) DEFAULT 0 NOT NULL 
, CONSTRAINT XPKCSM_ROLE PRIMARY KEY 
  (
    ROLE_ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX XPKCSM_ROLE ON CSM_ROLE (ROLE_ID ASC) 
      LOGGING 
      TABLESPACE WWFDATA 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 81920 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE WWFDATA 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 81920 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

CREATE UNIQUE INDEX XAK1CSM_ROLE ON CSM_ROLE (ROLE_NAME ASC, ENTERPRISE_NAME ASC) 
LOGGING 
TABLESPACE WWFDATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 81920 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

CREATE INDEX XIF506CSM_ROLE ON CSM_ROLE (ENTERPRISE_NAME ASC) 
LOGGING 
TABLESPACE ABCDATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 81920 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL;

ALTER TABLE CSM_ROLE
ADD CONSTRAINT CSM_REL_9 FOREIGN KEY
(
  ENTERPRISE_NAME 
)
REFERENCES CSM_ENTERPRISE
(
  ENTERPRISE_NAME 
)
ON DELETE CASCADE ENABLE;
